// tb_mem -- THE MEMORY SECTION IS IN THE MACHINE, AND ITS CLOCK RUNS.
//
// The first rung for MemC + MemD + MemX, and deliberately the same one the
// processor started on: before anything can be asked of a board, the board has
// to be in a machine that elaborates and has to be clocked.
//
// `dorado_mem` is ContA + ContB + ProcH + ProcL + MemC + MemD + MemX --
// generated by tools/sil_backplane.py like the other configurations, wired by
// NAME across the backplane. The Control and Processor boards are there
// because a memory reference does not exist without them: the microinstruction
// that issues it comes from ContA/ContB, and the address and data ride the
// ProcH/ProcL buses.
//
// WHAT THIS GATES. Each memory board takes its own backplane clock -- PARC
// gives every slot a separate one, `CLK.mc'`, `CLK.md'`, `CLK.mx'` -- and fans
// it out into local `clk0'`/`clk1'` nets. But the fan-out is GATED: the first
// stage ANDs the backplane clock with `MemClkEnable'`, which ContA drives from
// a pair of MC10231 flip-flops. So a memory board's local clock is SUPPOSED to
// be dead until the Control section enables it, and "the clock runs" is the
// wrong thing to assert.
//
// What is asserted instead is the CONSISTENCY: a board's local clock runs if
// and only if its enable is asserted. That catches a broken gate in either
// direction -- a clock that never starts when enabled, and one that free-runs
// when it should be held off.
//
// MEASURED, out of reset with nothing initialised:
//
//     MemC  MemClkEnable'a=1 CLKEnable'b=1   local clock  0 edges   gated off
//     MemD  MemClkEnable'a=1                 local clock  0 edges   gated off
//     MemX  MemClkEnable'c=0 ClkEnable'a=0   local clock  1250      running
//
// which is correct for MemC and MemD -- ContA holds `MemClkEnable'a` high
// until microcode says otherwise -- and is a FINDING for MemX: its enables are
// undriven. ContA drives `MemClkEnable'a` and `'b`; MemX asks for `'c`, and no
// board in the machine drives that. Its clock therefore runs only because an
// unconnected net floats to the enabled state. Note the pins do not settle it
// either: all three memory boards take theirs on C12 while ContA drives on C17
// and C20, which is exactly the non-straight-through backplane this machine is
// wired by NAME to model. Whether `'c` is a third fan-out copy PARC's wire list
// spells differently, or a genuinely separate line, is not established here.
//
// It is a floor, not a claim that the memory section works: nothing here
// issues a reference, reads the Map, or touches the cache.

`default_nettype none

module tb_mem;

  reg sys_clk = 1'b0;
  always #1 sys_clk = ~sys_clk;

  // The Dorado clock, divided down from the fabric clock the same way the
  // other testbenches do it -- the BaseBoard is not in this configuration, so
  // the backplane clocks are driven here.
  reg [3:0] ckd = 4'd0;
  always @(posedge sys_clk) ckd <= ckd + 4'd1;
  wire mclk = ckd[3];

  reg [2:0] addr_n = 3'b111;
  reg [8:0] cpout  = 9'd0;
  reg       strb_n = 1'b1;
  reg       setrun = 1'b0, setss_n = 1'b1;

  dorado_mem m (
      .sys_clk(sys_clk),
      .CLK_ca_p_(mclk), .CLK_cb_p_(mclk), .CLK_ph_p_(mclk), .CLK_pl_p_(mclk),
      .CLK_mc_p_(mclk), .CLK_md_p_(mclk), .CLK_mx_p_(mclk),
      .CPAddr_0_p_(addr_n[2]), .CPAddr_1_p_(addr_n[1]), .CPAddr_2_p_(addr_n[0]),
      .CPOut_0(cpout[8]), .CPOut_1(cpout[7]), .CPOut_2(cpout[6]),
      .CPOut_3(cpout[5]), .CPOut_4(cpout[4]), .CPOut_5(cpout[3]),
      .CPOut_6(cpout[2]), .CPOut_7(cpout[1]), .CPOut_8(cpout[0]),
      .CPStrb_p_(strb_n), .SetRun(setrun), .SetSS_p_(setss_n)
  );

  // The local clock fan-out on each memory board.
  integer nc, nd, nx, i;
  reg pc, pd, px;

  initial begin
    repeat (200) @(posedge sys_clk);
    pc = m.b_MemC.clk0_p_A;
    pd = m.b_MemD.clk0_p_B;
    px = m.b_MemX.Clk0_p_Aa;
    nc = 0; nd = 0; nx = 0;

    for (i = 0; i < 20000; i = i + 1) begin
      @(posedge sys_clk);
      if (m.b_MemC.clk0_p_A  !== pc) begin nc = nc + 1; pc = m.b_MemC.clk0_p_A;  end
      if (m.b_MemD.clk0_p_B  !== pd) begin nd = nd + 1; pd = m.b_MemD.clk0_p_B;  end
      if (m.b_MemX.Clk0_p_Aa !== px) begin nx = nx + 1; px = m.b_MemX.Clk0_p_Aa; end
    end

    $display("tb_mem: seven boards -- ContA ContB ProcH ProcL MemC MemD MemX");
    $display("tb_mem: local clock edges over 20,000 sys_clk: MemC %0d, MemD %0d, MemX %0d",
             nc, nd, nx);
    $display("tb_mem: clock ENABLES -- MemC MemClkEnable'a=%b CLKEnable'b=%b | MemD MemClkEnable'a=%b | MemX MemClkEnable'c=%b ClkEnable'a=%b",
             m.b_MemC.MemClkEnable_p_a, m.b_MemC.CLKEnable_p_b,
             m.b_MemD.MemClkEnable_p_a,
             m.b_MemX.MemClkEnable_p_c, m.b_MemX.ClkEnable_p_a);

    // The property: local clock runs IFF the board's enable is asserted
    // (the enables are active low).
    if ((m.b_MemC.MemClkEnable_p_a == 1'b0) != (nc != 0))
      $fatal(1, "MemC: enable=%b but local clock edges=%0d -- the gate is inconsistent",
             m.b_MemC.MemClkEnable_p_a, nc);
    if ((m.b_MemD.MemClkEnable_p_a == 1'b0) != (nd != 0))
      $fatal(1, "MemD: enable=%b but local clock edges=%0d -- the gate is inconsistent",
             m.b_MemD.MemClkEnable_p_a, nd);
    if ((m.b_MemX.MemClkEnable_p_c == 1'b0) != (nx != 0))
      $fatal(1, "MemX: enable=%b but local clock edges=%0d -- the gate is inconsistent",
             m.b_MemX.MemClkEnable_p_c, nx);

    $display("tb_mem: each memory board's local clock follows its MemClkEnable'.");
    $display("tb_mem: MemC and MemD are correctly held off by ContA; MemX runs because");
    $display("tb_mem:   its MemClkEnable'c has no driver in the machine -- see the header.");
    $finish;
  end
endmodule
`default_nettype wire
