// tb_mem -- THE MEMORY SECTION IS IN THE MACHINE, AND ITS CLOCK RUNS.
//
// The first rung for MemC + MemD + MemX, and deliberately the same one the
// processor started on: before anything can be asked of a board, the board has
// to be in a machine that elaborates and has to be clocked.
//
// `dorado_mem` is ContA + ContB + ProcH + ProcL + MemC + MemD + MemX --
// generated by tools/sil_backplane.py like the other configurations, wired by
// NAME across the backplane. The Control and Processor boards are there
// because a memory reference does not exist without them: the microinstruction
// that issues it comes from ContA/ContB, and the address and data ride the
// ProcH/ProcL buses.
//
// WHAT THIS GATES. Each memory board takes its own backplane clock -- PARC
// gives every slot a separate one, `CLK.mc'`, `CLK.md'`, `CLK.mx'` -- and fans
// it out into local `clk0'`/`clk1'` nets. But the fan-out is GATED: the first
// stage ANDs the backplane clock with `MemClkEnable'`, which ContA drives from
// a pair of MC10231 flip-flops. So a memory board's local clock is SUPPOSED to
// be dead until the Control section enables it, and "the clock runs" is the
// wrong thing to assert.
//
// What is asserted instead is the CONSISTENCY: a board's local clock runs if
// and only if its enable is asserted. That catches a broken gate in either
// direction -- a clock that never starts when enabled, and one that free-runs
// when it should be held off.
//
// MEASURED, out of reset with nothing initialised:
//
//     MemC  MemClkEnable'a=1 CLKEnable'b=1   local clock  0 edges   gated off
//     MemD  MemClkEnable'a=1                 local clock  0 edges   gated off
//     MemX  MemClkEnable'c=0 ClkEnable'a=0   local clock  1250      running
//
// which is correct for MemC and MemD -- ContA holds `MemClkEnable'a` high
// until microcode says otherwise -- and is a FINDING for MemX: its enables are
// undriven. ContA drives `MemClkEnable'a` and `'b`; MemX asks for `'c`, and no
// board in the machine drives that. Its clock therefore runs only because an
// unconnected net floats to the enabled state. Note the pins do not settle it
// either: all three memory boards take theirs on C12 while ContA drives on C17
// and C20, which is exactly the non-straight-through backplane this machine is
// wired by NAME to model. Whether `'c` is a third fan-out copy PARC's wire list
// spells differently, or a genuinely separate line, is not established here.
//
// STARTING THE MACHINE MAKES IT OSCILLATE, and that is the most useful thing
// this gate has found. `+define+MEM_RUN` runs run-test's own start sequence
// (Clock, ClrStop+ClrMIR+ClrCT+Freeze, SetSS, ClrStop+SetRun) and then asserts
// `SetRunRfsh` -- a backplane line the BASEBOARD drives, and the one that
// makes ContA assert `WantRunRfsh` -> `RunRefresh` -> `dMemRun`, which is half
// of `MemClkEnable'`. The other half is `dStop`, so the memory clocks come on
// when the machine RUNS and refresh is asked for. With no BaseBoard in this
// configuration the testbench drives that line itself, exactly as the
// BaseBoard would.
//
// The result is `Active region did not converge after 100 tries` -- the SAME
// failure `machine-test` has on the eleven-board machine, reproduced here on
// SEVEN, which is a much smaller thing to debug. Note `loop-check` passes, so
// it is not a combinational loop the cell files can show; it is a machine-level
// oscillation that only appears once the memory clocks are enabled.
//
// That is why the experiment is behind a define: the gate proper stays on the
// property it can prove, and the convergence failure is recorded rather than
// left as a red gate.
//
// It is a floor, not a claim that the memory section works: nothing here
// issues a reference, reads the Map, or touches the cache.

`default_nettype none

module tb_mem;


  // THE OVERSAMPLING RATIO -- sys_clk per microinstruction. SYSPER reaches only
  // `cell_CLOCKGEN`, which lives on the BaseBoard, so a sub-machine's clock is
  // whatever its bench drives; this one used to hard-code a divide-by-16 and
  // therefore only ever ran at 16x. Real time needs sys_clk = SYSPER x 16.67
  // MHz and measured Fmax is 48.99 MHz, so SYSPER=2 is the target.
  //
  //     make -C verilog/verilator <gate> SYSPER=2
`ifndef SYSPER_OVERRIDE
  `define SYSPER_OVERRIDE 16
`endif
  localparam integer SYSPER = `SYSPER_OVERRIDE;
  // SCALE A FABRIC-CYCLE WAIT so it means the same amount of DORADO time at any
  // ratio. NOT `SYSPER / 16` -- integer division gives ZERO below 16x, which
  // turns every `repeat` into no wait at all.
  function automatic integer WT(input integer n);
    begin
      // ROUND TO NEAREST, not toward zero. Truncation flattens the SHAPE of a
      // waveform at low ratios -- at SYSPER=4 a 4-cycle low and a 6-cycle
      // setup both truncate to 1, turning 4:6 into 1:1 -- and the single-step
      // chain depends on strobe SPACING (SetRun must survive three RunClk'
      // edges). That cost step-test at 4x and nothing else. Exact at
      // SYSPER=16, where WT(n) = n with no remainder.
      WT = (n * SYSPER + 8) / 16;
      if (WT < 1) WT = 1;
    end
  endfunction

  reg sys_clk = 1'b0;
  always #1 sys_clk = ~sys_clk;

  // The Dorado clock, divided down from the fabric clock the same way the
  // other testbenches do it -- the BaseBoard is not in this configuration, so
  // the backplane clocks are driven here.
  reg [3:0] ckd = 4'd0;
  // At SYSPER=16 this is bit for bit the counter it replaces:
  // ckd counts 0..15 and mclk is ckd >= 8, i.e. ckd[3].
  always @(posedge sys_clk)
    ckd <= (ckd == SYSPER - 1) ? 4'd0 : ckd + 4'd1;
  wire mclk = (ckd >= SYSPER / 2);

  reg [2:0] addr_n = 3'b111;
  reg [8:0] cpout  = 9'd0;
  reg       strb_n = 1'b1;
  reg       setrun = 1'b0, setss_n = 1'b1;
  // `SetRunRfsh` is a backplane line the BASEBOARD drives -- it is what makes
  // ContA assert `WantRunRfsh`, which sets `RunRefresh` and `dMemRun`, which
  // is half of `MemClkEnable'`. There is no BaseBoard in this configuration,
  // so the testbench drives it exactly as the BaseBoard would.
  reg       setrunrfsh = 1'b0;

  dorado_mem m (
      .sys_clk(sys_clk),
      .CLK_ca_p_(mclk), .CLK_cb_p_(mclk), .CLK_ph_p_(mclk), .CLK_pl_p_(mclk),
      .CLK_mc_p_(mclk), .CLK_md_p_(mclk), .CLK_mx_p_(mclk),
      .CPAddr_0_p_(addr_n[2]), .CPAddr_1_p_(addr_n[1]), .CPAddr_2_p_(addr_n[0]),
      .CPOut_0(cpout[8]), .CPOut_1(cpout[7]), .CPOut_2(cpout[6]),
      .CPOut_3(cpout[5]), .CPOut_4(cpout[4]), .CPOut_5(cpout[3]),
      .CPOut_6(cpout[2]), .CPOut_7(cpout[1]), .CPOut_8(cpout[0]),
      .CPStrb_p_(strb_n), .SetRun(setrun), .SetSS_p_(setss_n),
      .SetRunRfsh(setrunrfsh)
  );

  localparam integer GAP = (200 * SYSPER) / 16;
  integer k;
  task strobe(input [2:0] fn, input [7:0] data, input ss);
    begin
      addr_n = ~fn; cpout = {ss, data}; setss_n = ~ss;
      repeat (WT(4)) @(posedge sys_clk); strb_n = 1'b0;
      repeat (WT(8)) @(posedge sys_clk); strb_n = 1'b1;
      repeat (GAP) @(posedge sys_clk);
    end
  endtask

  // The local clock fan-out on each memory board.
  integer nc, nd, nx, i;
  reg pc, pd, px;

  initial begin
    repeat (WT(200)) @(posedge sys_clk);
    pc = m.b_MemC.clk0_p_A;
    pd = m.b_MemD.clk0_p_B;
    px = m.b_MemX.Clk0_p_Aa;
    nc = 0; nd = 0; nx = 0;

    for (i = 0; i < 20000; i = i + 1) begin
      @(posedge sys_clk);
      if (m.b_MemC.clk0_p_A  !== pc) begin nc = nc + 1; pc = m.b_MemC.clk0_p_A;  end
      if (m.b_MemD.clk0_p_B  !== pd) begin nd = nd + 1; pd = m.b_MemD.clk0_p_B;  end
      if (m.b_MemX.Clk0_p_Aa !== px) begin nx = nx + 1; px = m.b_MemX.Clk0_p_Aa; end
    end

    $display("tb_mem: seven boards -- ContA ContB ProcH ProcL MemC MemD MemX");
    $display("tb_mem: local clock edges over 20,000 sys_clk: MemC %0d, MemD %0d, MemX %0d",
             nc, nd, nx);
    $display("tb_mem: clock ENABLES -- MemC MemClkEnable'a=%b CLKEnable'b=%b | MemD MemClkEnable'a=%b | MemX MemClkEnable'c=%b ClkEnable'a=%b",
             m.b_MemC.MemClkEnable_p_a, m.b_MemC.CLKEnable_p_b,
             m.b_MemD.MemClkEnable_p_a,
             m.b_MemX.MemClkEnable_p_c, m.b_MemX.ClkEnable_p_a);

    // The property: local clock runs IFF the board's enable is asserted
    // (the enables are active low).
    if ((m.b_MemC.MemClkEnable_p_a == 1'b0) != (nc != 0))
      $fatal(1, "MemC: enable=%b but local clock edges=%0d -- the gate is inconsistent",
             m.b_MemC.MemClkEnable_p_a, nc);
    if ((m.b_MemD.MemClkEnable_p_a == 1'b0) != (nd != 0))
      $fatal(1, "MemD: enable=%b but local clock edges=%0d -- the gate is inconsistent",
             m.b_MemD.MemClkEnable_p_a, nd);
    if ((m.b_MemX.MemClkEnable_p_c == 1'b0) != (nx != 0))
      $fatal(1, "MemX: enable=%b but local clock edges=%0d -- the gate is inconsistent",
             m.b_MemX.MemClkEnable_p_c, nx);

    $display("tb_mem: each memory board's local clock follows its MemClkEnable'.");
    $display("tb_mem: MemC and MemD are correctly held off by ContA; MemX runs because");
    $display("tb_mem:   its MemClkEnable'c has no driver in the machine -- see the header.");

    // ---- NOW START THE MACHINE -------------------------------------------
`ifdef MEM_RUN
    // MemClkEnable'a is a wired-OR of two MC10231s on ContA: one latches
    // `dMemRun` (set by `RunRefresh`), the other `dStop`. So the memory clocks
    // come on when the machine RUNS. This is run-test's own start sequence.
    strobe(3'd1, 8'h21, 1'b0);              // Clock: InhibitCAHolds+ClrReady
    strobe(3'd0, 8'h4E, 1'b0); setrun = 0;  // ClrStop+ClrMIR+ClrCT+Freeze
    strobe(3'd0, 8'h00, 1'b1); setss_n = 0; // undo the clears, SetSS
    strobe(3'd0, 8'h41, 1'b1); setrun = 1;  // ClrStop AND SetRun together
    setrunrfsh = 1'b1;                      // ...and what the BaseBoard asserts
    repeat (WT(400)) @(posedge sys_clk);

    pc = m.b_MemC.clk0_p_A; pd = m.b_MemD.clk0_p_B; px = m.b_MemX.Clk0_p_Aa;
    nc = 0; nd = 0; nx = 0;
    for (i = 0; i < 20000; i = i + 1) begin
      @(posedge sys_clk);
      if (m.b_MemC.clk0_p_A  !== pc) begin nc = nc + 1; pc = m.b_MemC.clk0_p_A;  end
      if (m.b_MemD.clk0_p_B  !== pd) begin nd = nd + 1; pd = m.b_MemD.clk0_p_B;  end
      if (m.b_MemX.Clk0_p_Aa !== px) begin nx = nx + 1; px = m.b_MemX.Clk0_p_Aa; end
    end
    $display("tb_mem: machine RUNNING -- MemClkEnable'a=%b, local clock edges MemC %0d, MemD %0d, MemX %0d",
             m.b_MemC.MemClkEnable_p_a, nc, nd, nx);
    if (nc == 0 || nd == 0)
      $fatal(1, "the memory clocks did not start when the machine ran (MemC %0d, MemD %0d)", nc, nd);
    $display("tb_mem: THE MEMORY BOARDS CLOCK WHEN THE MACHINE RUNS.");
`endif
    $finish;
  end
endmodule
`default_nettype wire
