#!/usr/bin/env python3
"""Generate a Quartus project for the eleven-board Dorado, to get real fit numbers.

WHY THIS IS GENERATED. The machine's top module has 386 ports -- 148 in, 238
out -- because every cable leaving the backplane is a port. A DE10-Nano cannot
pin that, so every port except the fabric clock is declared a VIRTUAL PIN:
Quartus then places and routes the logic without needing a physical pad, which
is the standard way to fit-check a module that is not the whole chip. Listing
385 of them by hand is not a thing anyone should do twice.

WHAT THIS ANSWERS. The capacity case for this design has so far been
arithmetic -- 2,824 cell instances against a DE10-Nano's 41,910 ALMs, and 246
M10K worst case against 557 available (tools/sil_ram_groups.py, measured). What
has never been run is Quartus itself, so ALM/M10K/Fmax are unknown, and Fmax is
the one that decides whether the machine can run at its real 60 ns
microinstruction cycle.

USAGE
    python3 tools/quartus_project.py            # writes fpga/quartus/dorado.qsf
    cd fpga/quartus && quartus_sh --flow compile dorado
"""
import glob
import os
import re
import sys

DEVICE = "5CSEBA6U23I7"          # DE10-Nano, Cyclone V SE A6
FAMILY = "Cyclone V"
TOP = "dorado_backplane"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "fpga", "quartus")


def ports(path, module):
    t = open(path).read()
    i = t.index("module " + module)
    j = t.index(");", i)
    return re.findall(r'\b(?:input|output|inout)\s+(?:wire\s+)?(\w+)', t[i:j])


def main() -> int:
    top_v = os.path.join(ROOT, "verilog", "generated", TOP + ".v")
    if not os.path.exists(top_v):
        print(f"FAIL: {top_v} missing -- run `make -C verilog backplane` first")
        return 1
    names = ports(top_v, TOP)
    if "sys_clk" not in names:
        print("FAIL: the top module has no sys_clk to drive the fabric")
        return 1

    # The boards named in the top module's own Configuration comment, plus the
    # cell library. Taking the board list from the generated file keeps this
    # honest if the configuration changes.
    conf = re.search(r'// Configuration: (.+)', open(top_v).read())
    boards = conf.group(1).split() if conf else []
    srcs = [top_v]
    for b in boards:
        hits = sorted(glob.glob(os.path.join(ROOT, "verilog", "generated", b + "-Rev-*.v")))
        hits += sorted(glob.glob(os.path.join(ROOT, "verilog", "generated", b + ".v")))
        if not hits:
            print(f"FAIL: no generated Verilog for board {b}")
            return 1
        srcs.append(hits[0])
    cells = sorted(glob.glob(os.path.join(ROOT, "verilog", "cells", "cell_*.v")))
    if not cells:
        print("FAIL: no cell models found")
        return 1
    srcs += cells

    # THE BASEBOARD'S TWO REAL CORES. cell_MCS6502 and cell_MCS6532 are
    # wrappers -- they instantiate chip_6502 and M6532, which are vendored
    # rather than generated, so a cell_*.v glob misses them and every BaseBd
    # package fails to elaborate. The Verilator benches pick them up through
    # -Iverilog/vendor/6502 -Iverilog/vendor/riot; Quartus needs them listed.
    vendor = []
    for sub in ("6502", "riot"):
        vendor += sorted(glob.glob(os.path.join(ROOT, "verilog", "vendor", sub, "*.v")))
        vendor += sorted(glob.glob(os.path.join(ROOT, "verilog", "vendor", sub, "*.sv")))
    if not vendor:
        print("FAIL: no vendored 6502/6532 cores found")
        return 1
    srcs += vendor

    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, "dorado.qpf"), "w") as f:
        f.write("QUARTUS_VERSION = \"17.0\"\nPROJECT_REVISION = \"dorado\"\n")

    with open(os.path.join(OUT, "dorado.qsf"), "w") as f:
        w = f.write
        w("# GENERATED by tools/quartus_project.py -- do not edit.\n#\n")
        w("# Every port but sys_clk is a VIRTUAL PIN: the machine has 386 ports\n")
        w("# because each cable off the backplane is one, and no DE10-Nano can pin\n")
        w("# that. Virtual pins let Quartus place and route the logic anyway,\n")
        w("# which is what gives real ALM/M10K/Fmax rather than an estimate.\n\n")
        w(f'set_global_assignment -name FAMILY "{FAMILY}"\n')
        w(f'set_global_assignment -name DEVICE {DEVICE}\n')
        w(f'set_global_assignment -name TOP_LEVEL_ENTITY {TOP}\n')
        w('set_global_assignment -name PROJECT_OUTPUT_DIRECTORY output_files\n')
        # THE PROM CELLS $readmemh PATHS RELATIVE TO THE REPO ROOT --
        # verilog/proms/packages/<board>-<pkg>.mem -- and Quartus runs from the
        # PROJECT directory, so without this every PROM package fails to
        # elaborate with "can't open Verilog Design File". SEARCH_PATH is what
        # Quartus uses to resolve memory initialisation files.
        w('set_global_assignment -name SEARCH_PATH "../.."\n')
        w('set_global_assignment -name SDC_FILE dorado.sdc\n')
        w('set_global_assignment -name NUM_PARALLEL_PROCESSORS ALL\n')
        # The generator emits plain Verilog-2001 plus a little SystemVerilog.
        w('set_global_assignment -name VERILOG_INPUT_VERSION SYSTEMVERILOG_2005\n\n')
        for s in srcs:
            rel = os.path.relpath(s, OUT)
            w(f'set_global_assignment -name SYSTEMVERILOG_FILE {rel}\n')
        w("\n# ---- virtual pins ----\n")
        n = 0
        for p in names:
            if p == "sys_clk":
                continue
            w(f'set_instance_assignment -name VIRTUAL_PIN ON -to {p}\n')
            n += 1
        w(f"\n# {n} virtual pins, 1 real ({len(names)} ports total)\n")

    with open(os.path.join(OUT, "dorado.sdc"), "w") as f:
        # 20 ns is a deliberately loose starting constraint: the point of the
        # first run is to LEARN Fmax, not to meet a target. The real machine's
        # microinstruction cycle is 60 ns and this RTL oversamples it, so the
        # fabric clock needs to be a multiple of that -- which is exactly what
        # the reported Fmax will tell us is possible.
        f.write("create_clock -name sys_clk -period 20.000 [get_ports {sys_clk}]\n")
        f.write("derive_clock_uncertainty\n")

    print(f"wrote {OUT}/dorado.qsf")
    print(f"  device {DEVICE} ({FAMILY}), top {TOP}")
    print(f"  boards: {' '.join(boards)}")
    print(f"  {len(srcs)} source files ({len(cells)} cells, {len(vendor)} vendored)")
    print(f"  {n} virtual pins, 1 real pin")
    return 0


if __name__ == "__main__":
    sys.exit(main())
